apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go-api-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: service.yaml
images:
  - name: APP_IMAGE
    newName: ghcr.io/example/go-api
    newTag: latest
# replica count for dev (1 pod is enough)
replicas:
  - name: go-api
    count: 1
